- name: include vars
  include_vars: jdk1.8.yml
- name:  unarchive jdk
  unarchive: src={{java_file}} dest=/usr/local/
- name:  set path variable
  lineinfile: dest=/etc/profile line="export JAVA_HOME={{java_home}}\n
    export PATH=$JAVA_HOME/bin:$PATH\n
    export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"
- name: reload config
  shell: source /etc/profile
  args:
    executable: /bin/bash
